### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#65]
Coding style should be consistent and aligned with the style guideline.
- [ ] Add function headers comments
- [ ] Fix styling issues with filenames & capitalization/variable names in code

**Comment by AmnesiacSloth** [comment]
@ChrisChen0803 @KenKunoo 

Finished styling on a couple js files. But I believe we have redundant js files. For example p_fb.js and Professor_Feedback.js both have the same functionality.

 Chris, did you or adam work on any of these files ? I'm afraid to delete them because when Kenny and I worked on these files there were function declarations and definitions in files like Professor_Feedback.js that weren't being used anywhere. Just lmk if there's any code in there that we should move elsewhere or if its cool to get rid of them 👍🏼 
 
## HTML Files & their corresponding script files 
### includes scripts that are commented out 
 - landingpage.html
    - NONE
 - login.html 
    - authentication.js
 - professor_feedback_view.html
    - p_fb.js
    - Single_Comment.js **Commented Out**
    - professorFeedback.js **Commented Out**
 - professor_modify_category.html
    - script.js
 - student_add_comment.html
    - add_feedback.js 
    - script.js **Commented Out**
    - Single_Comment.js **Commented Out**
- student_add_feedback_view.html
   - student_fb_view.js
   - Single_Comment.js **Commented Out**
   - studentFeedback.js **Commented Out**
- view_feedback.html
   - view_fb.js
